### ISSUE TITLE
Source for t235.jar?

### ISSUE THREAD

**Issue by nathanielw** [smanoharan/235-lab-verifier#1]
Hi Siva, 
it's probably a really long shot, but I was wondering if you happen to still have the source for generating the `t235.jar` file. We've had a few people running into a couple of false-positives and false-negatives with the verifier, with the bugs seeming to occur when there's a loop on the machine's accepting state. From a quick look, this seems to coming from within in the modified Tuatara code. I guess I could try decompiling the bytecode to fix the bug, but figured I'd give this a shot first :smiley: 
Cheers.

**Comment by smanoharan** [comment]
Hi Nathaniel,

I've sent you the source via email.
